name: driplix
description: A picture feed app like Pinterest - cross-platform for iOS, web, and Android
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.4
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/getAllMockPost.json
    - assets/images/logos/
    - assets/images/navigation/
    - assets/images/navigation/Searchbar/
    - assets/images/icons/
    - assets/images/homepage/
    - assets/images/mockimage/
    - assets/images/wardrobe/
    - assets/images/signup/
    - assets/images/signin/
    - assets/images/post/
    - assets/post/
